// <auto-generated />
using System;
using FamilyPlanner.api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyPlanner.api.Migrations
{
    [DbContext(typeof(FamilyPlannerDataContext))]
    partial class FamilyPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FamilyPlanner.api.Entities.GroceryItem", b =>
                {
                    b.Property<uint?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<int?>("GroceryDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GroceryItem");
                });

            modelBuilder.Entity("FamilyPlanner.api.Entities.GroceryListItem", b =>
                {
                    b.Property<uint?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("GroceryItemId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("MealId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("GroceryItemId");

                    b.HasIndex("MealId");

                    b.ToTable("GroceryListItem");
                });

            modelBuilder.Entity("FamilyPlanner.api.Entities.Meal", b =>
                {
                    b.Property<uint?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MealTypes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipeUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FamilyPlanner.api.Entities.GroceryListItem", b =>
                {
                    b.HasOne("FamilyPlanner.api.Entities.GroceryItem", "GroceryItem")
                        .WithMany()
                        .HasForeignKey("GroceryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyPlanner.api.Entities.Meal", "Meal")
                        .WithMany("GroceryListItems")
                        .HasForeignKey("MealId");

                    b.Navigation("GroceryItem");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FamilyPlanner.api.Entities.Meal", b =>
                {
                    b.Navigation("GroceryListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
